version: '3.8'

services:
  assistant-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/assistant.db
      - LMSTUDIO_BASE_URL=http://host.docker.internal:1234
      - API_HOST=0.0.0.0
      - API_PORT=8000
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=assistant
      - POSTGRES_USER=assistant
      - POSTGRES_PASSWORD=assistant_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - assistant-api
    restart: unless-stopped

volumes:
  postgres_data:
